### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sm27**
The script tests for 2.15 as well.

### CODE REVIEW

**Comment by sm27** [comment]
Please review

**Comment by johspaeth** [comment]
Thanks a lot, that must have been slipped through.

**Comment by sm27** [comment]
Thanks - Shall we extend the utility to scan all jar/war files within a
given folder in one go?

**Comment by johspaeth** [comment]
@sm27 That's is a great idea! Do you want to create a PR for it?

**Pull request merged**
